export enum Permission {
  READ_USER = 'READ_USER',
  WRITE_USER = 'WRITE_USER',
  // ROLE
  READ_ROLE = 'READ_ROLE',
  WRITE_ROLE = 'WRITE_ROLE',
  // BOOK
  READ_BOOK = 'READ_BOOK',
  WRITE_BOOK = 'WRITE_BOOK',
  // BOOKSTORE
  READ_BOOKSTORE = 'READ_BOOKSTORE',
  WRITE_BOOKSTORE = 'WRITE_BOOKSTORE',
}
