version: '3'
services:
  od-api-dev:
    build:
      context: ../
      dockerfile: dev.Dockerfile
    image: od-api:dev
    ports:
      - "3030:3030"
    volumes:
     - "./../:/usr/src/app"
    env_file:
      - "./../.env"
    privileged: true
