version: '3'
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: 1196
      POSTGRES_USER: postgres
      POSTGRES_DB: storedb
    ports:
      - "7201:5432"
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
