version: '3'
services:
  od-api-prod:
    build:
      context: ../
      dockerfile: ./dockerfiles/prod.Dockerfile
    image: od-api:latest
    ports:
      - "3030:3030"
    env_file:
      - "./../.env"
    privileged: true
